[versions]
agp = "8.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
navigationFragment = "2.9.6"
navigationUi = "2.9.6"
firebaseCrashlytics = "20.0.4"
googleGmsGoogleServices = "4.4.4"
googleFirebaseCrashlytics = "3.0.6"
appUpdate = "2.1.0"
firebaseMessaging = "25.0.1"
sdp = "1.1.1"
gson = "2.13.2"
retrofit = "3.0.0"
okhttp = "5.3.2"
spinkit = "1.4.0"
glide = "5.0.5"
cropper = "4.7.0"
dotsindicator = "5.1.0"
otpview = "1.1.2"
circleimage = "3.1.0"
gifdrawable = "1.2.30"
razorpay = "1.6.11"
installreferrer = "2.2"
snacky = "1.1.6"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
app-update = { group = "com.google.android.play", name = "app-update", version.ref = "appUpdate" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
sdp = { module = "com.intuit.sdp:sdp-android", version.ref = "sdp" }
ssp = { module = "com.intuit.ssp:ssp-android", version.ref = "sdp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
spinkit = { module = "com.github.ybq:Android-SpinKit", version.ref = "spinkit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "cropper" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
otpview = { module = "com.github.aabhasr1:OtpView", version.ref = "otpview" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimage" }
gifdrawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "gifdrawable" }
razorpay-checkout = { module = "com.razorpay:checkout", version.ref = "razorpay" }
installreferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "installreferrer" }
snacky = { module = "com.github.matecode:Snacky", version.ref = "snacky" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }

